<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-08-01 12:33
=======
# Generated by Django 3.2.6 on 2021-08-07 18:26
>>>>>>> 1a4848ef8ad436fcf663dbc0ffde956ead0b32ec

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Achiever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
=======
            name='Achievers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athleteImage', models.ImageField(upload_to='athleteImages')),
                ('name', models.CharField(max_length=100)),
                ('medals', models.TextField(max_length=100)),
                ('sports_category', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=256)),
                ('detailed_info_link', models.URLField(blank=True, null=True)),
>>>>>>> 1a4848ef8ad436fcf663dbc0ffde956ead0b32ec
            ],
        ),
    ]
